# Generated by Django 3.2.5 on 2021-08-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250)),
                ('ingredient_serving_size', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=2)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor')),
            ],
        ),
    ]
