# Generated by Django 3.2.5 on 2021-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20210810_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='serving_size_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
